HairSalon.Solution/HairSalon/Models/Clients.cs
  
namespace HairSalon.Models
{
  public class Clients
  {
    public int ClientsId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public int StylistsId { get; set; }

    public virtual Stylists Stylists { get; set; }
  }


}

HairSalon.Solution/HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public virtual DbSet<Stylists> Stylists { get; set; }
    public DbSet<Clients> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon.Solution/HairSalon/Models/Stylists.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylists
    {
        public Stylists()
        {
            this.Clients = new HashSet<Clients>();
        }

        public int StylistsId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Specialty { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
    }
}

HairSalon.Solution/HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    
    {
        List<Clients> model = _db.Clients.Include(c => c.Stylists).ToList();
        return View(model);
    }
    

    public ActionResult Create()
    {
        ViewBag.StylistsId = new SelectList(_db.Stylists, "StylistsId", "FirstName", "LastName");
        return View();
    }

    [HttpPost]
    public ActionResult Create(Clients client)
    {
        _db.Clients.Add(client);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        Clients thisClient = _db.Clients.FirstOrDefault(c => c.ClientsId == id);
        return View(thisClient);
    }
        public ActionResult Delete(int id)
    {
        var thisClient = _db.Clients.FirstOrDefault(c => c.ClientsId == id);
        return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisClient = _db.Clients.FirstOrDefault(c => c.ClientsId == id);
        _db.Clients.Remove(thisClient);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
        public ActionResult Edit(int id)
    {
        var thisClient = _db.Clients.FirstOrDefault(c => c.ClientsId == id);
        ViewBag.StylistsId = new SelectList(_db.Stylists, "StylistsId", "FirstName", "LastName");
        return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Clients client)
    {
        _db.Entry(client).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

  }
}

HairSalon.Solution/HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon.Solution/HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }
            
    [HttpGet]    
    public ActionResult Index()
    {
      List<Stylists> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylists stylists)
    {
      _db.Stylists.Add(stylists);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Stylists thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistsId == id);
      return View(thisStylist);
    }
     public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistsId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistsId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistsId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylists stylists)
    {
      _db.Entry(stylists).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

HairSalon.Solution/HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models
@model HairSalon.Models.Clients


<h4>Add a new client</h4>

@using (Html.BeginForm())
{
    <p>First Name 
    @Html.TextBoxFor(model => model.FirstName)</p>

    <p>Last Name
    @Html.TextBoxFor(model => model.LastName)</p>

   



    @Html.LabelFor(model => model.Stylists)
    @Html.DropDownList("StylistsId")
    <br>
    <br>

    <input type="submit" value="Add new client" class="btn btn-default" />

    
}
<p>@Html.ActionLink("Show all Clients", "Index")</p>

HairSalon.Solution/HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Clients


<h3>Are you sure you want to delete this?</h3>

@Html.DisplayNameFor(model => model.FirstName): @Html.DisplayFor(model => model.FirstName)
@Html.DisplayNameFor(model => model.LastName): @Html.DisplayFor(model => model.LastName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon.Solution/HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Clients


<h2>Client Details</h2>

<h3>@Html.DisplayNameFor(model => model.FirstName): 
  @Html.DisplayFor(model => model.FirstName)<h3>
  <h3>@Html.DisplayNameFor(model => model.LastName): 
    @Html.DisplayFor(model => model.LastName)</h3>

    
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.ClientsId })</p>
<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.ClientsId })</p>

HairSalon.Solution/HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Clients


<h2>Edit</h2>

<h4>Edit this client: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientsId)

    @Html.LabelFor(model => model.FirstName)
    @Html.EditorFor(model => model.FirstName)

    @Html.LabelFor(model => model.LastName)
    @Html.EditorFor(model => model.LastName)
    @Html.LabelFor(model => model.Stylists)
    @Html.DropDownList("StylistsId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>
</div>

HairSalon.Solution/HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Clients>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 

@foreach (Clients client in Model)
{
  <li>@Html.ActionLink($"{client.FirstName} {client.LastName}","Details", new { id = client.ClientsId }) | @client.Stylists.FirstName @client.Stylists.LastName, 
    @client.Stylists.Specialty</li>
  
}




<button>@Html.ActionLink("Add new clients", "Create")</button>
<br>
<br>

<button type="button" class="btn btn-warning">@Html.ActionLink("Home", "Index", "Home")</button>

HairSalon.Solution/HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="jumbotron">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  
 <a class="navbar-brand" href="#">Eau Claire Hair Salon</a>
 <div class= "buttons">
<button type="button" class="btn btn-warning">@Html.ActionLink("Home", "Index", "Home")</button>
<button type="button" class="btn btn-warning">@Html.ActionLink("See all Stylists", "Index", "Stylists")</button>
<button type="button" class="btn btn-warning">@Html.ActionLink("See all Clients", "Index", "Clients")</button>
</div>
</nav>
</div>

HairSalon.Solution/HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Eau Claire Hair</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body class= "container">
    
    @RenderBody()
    
  </body>
</html>

HairSalon.Solution/HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylists

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
    <p>First Name
    @Html.TextBoxFor(model => model.FirstName)</p>
    <p>Last Name
    @Html.TextBoxFor(model => model.LastName)</p>
    <p>Specialty
    @Html.TextBoxFor(model => model.Specialty)</p>
    <br>
    <br>
    <input type="submit" value="Add new stylist" /> 
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

<button type="button" class="btn btn-warning">@Html.ActionLink("Home", "Index", "Home")</button>

HairSalon.Solution/HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylists

<h2>Are you sure you want to delete this?</h2>

<h4>Name</h4>: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to categories", "Index")

HairSalon.Solution/HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Stylists;

<h2>Stylist Details</h2>
<hr />
<p>First Name: 
@Html.DisplayFor(model => model.FirstName)</p>
<p>Last Name: 
@Html.DisplayFor(model => model.LastName)</p>
<p>@Html.DisplayNameFor(model => model.Specialty): 
@Html.DisplayFor(model => model.Specialty)</p>

<ul>
@if (@Model.Clients.Count == 0)
{
  <p>No clients found.</p>
}

@foreach (Clients client in @Model.Clients)
{
  <li>Name: @client.FirstName, @client.LastName
      </li>
}
</ul>

<p>@Html.ActionLink("Back to stylists", "Index")</p>
<p>@Html.ActionLink("Edit Stylists", "Edit", new { id = Model.StylistsId })</p>
<p>@Html.ActionLink("Delete Stylists", "Delete", new { id = Model.StylistsId })</p>

HairSalon.Solution/HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylists

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StylistsId)

    @Html.LabelFor(model => model.FirstName)
    @Html.EditorFor(model => model.FirstName)

    @Html.LabelFor(model => model.LastName)
    @Html.EditorFor(model => model.LastName)

    @Html.LabelFor(model => model.Specialty)
    @Html.EditorFor(model => model.Specialty)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to stylists", "Index")</p>

HairSalon.Solution/HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylists>;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
} 

@foreach (Stylists stylist in Model)
{
    <li>@Html.ActionLink(
    $"{stylist.FirstName} {stylist.LastName}", "Details", new { id = stylist.StylistsId })
    @stylist.Specialty 
    </li>
}

<button>@Html.ActionLink("Add new stylists", "Create")</button>
<br>
<br>

<p><button type="button" class="btn btn-warning">@Html.ActionLink("Home", "Index", "Home")</button></p>